export const questions = [
  {
    q: 1,
    question: 'How many hours of loadshedding were there during 2021?',
    tip: '"Hours" are the number of hours in which a loadshedding level was in effect. For example, level 1 loadshedding',
    option1: '922',
    option2: '1,152',
    option3: '3,234',
    option4: '2,430',
    answer: '1,152',
    answered: false,
    selection: '',
    correct: false,
    incorrectResponse: 'Incorrect! The correct answer is 1,152',
    correctResponse:
      'Correct! With 1,152 hours of loadshedding, equal to 48 days, 2021 had the second highest number of loadshedding hours since 2015, which had 1,359 hours, or the equivalent of 56 days.',
  },
  {
    q: 2,
    question: 'Which months in 2021 had no loadshedding?',
    tip: '',
    option1: 'March & May',
    option2: 'July & September',
    option3: 'August & September',
    option4: 'October & November',
    answer: 'August & September',
    answered: false,
    selection: '',
    correct: false,
    incorrectResponse: 'Incorrect! The correct answer is August & September',
    correctResponse: 'Correct!',
  },
]
